services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "0.0.0.0:8080:8080"

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user
    ports:
      - "0.0.0.0:8089:8089"


  packed:
    build:
      context: ./packed
      dockerfile: Dockerfile
    container_name: packed
    ports:
      - "0.0.0.0:8085:8085"



  unpacked:
    build:
      context: ./unpacked
      dockerfile: Dockerfile
    container_name: unpacked
    ports:
      - "0.0.0.0:8082:8082"

  pantry:
    build:
      context: ./pantry
      dockerfile: Dockerfile
    container_name: pantry
    ports:
      - "0.0.0.0:8084:8084"
